#ifndef VALUES_H
#define VALUES_H

#define BLOCK 20

#define B_WIDHT 16
#define B_HEIGHT 16

#define WIDHT BLOCK * B_WIDHT
#define HEIGHT BLOCK * B_HEIGHT

#define SCREEN_WIDHT WIDHT
#define SCREEN_HEIGHT HEIGHT * 2

#define SCREEN_SIZE SCREEN_WIDHT*SCREEN_HEIGHT

#endif
